name: Build and Package

on:
  push:
    tags: '*'

jobs:
  publish-image:
    if:
      github.event.base_ref == 'refs/heads/main' || github.event.ref ==
      'refs/heads/main'
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: jupiterone/.github/.github/workflows/halo_publish_integration_collector_image.yaml@main
    secrets:
      GHCR_USERNAME: ${{ github.actor }}
      GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
